#!/bin/bash

if [ -z "$2" ]; then
	echo usage: $0 username domainname
	echo -domainname includes the .com/net/org
	exit
fi
USER=$1
DOMAIN=$2

#read the config file
source hosting.conf

#remove the symlink from apache
rm -f $HTTPD_HOSTS_EN$DOMAIN.conf

#remove the zone from named

#remove the symlink from named
rm -f $NAMED_HOSTS$DOMAIN.hosts
