#!/bin/bash

if [ -z "$2" ]; then
	echo usage: $0 username domainname
	echo -domainname includes the .com/net/org
	exit
fi
USER=$1
DOMAIN=$2

#read configuration from file
source hosting.conf

#create a user if they dont exist
USER_NOEXIST=`id "$USER" 2>&1| grep -i "no such user"`
if [ -n "$USER_NOEXIST" ]; then
	#use grep "^$i" /etc/passwd | cut -d: -f6 
	#if they dont exist but have a home directory, move it
	if [ -d "/home/$USER" ]; then
		mv /home/$USER /home/tmp$USER
	fi
	useradd -d /home/$USER $USER	

	#clean up
	if [ -d "/home/tmp$USER" ]; then
		mv /home/tmp$USER/* /home/$USER/.
		rmdir /home/tmp$USER
	fi
fi

#create the directories if needed
if [ ! -d "/home/$USER" ]; then
	mkdir /home/$USER
fi

if [ ! -d "/home/$USER/www" ]; then
	mkdir /home/$USER/www
fi

if [ ! -d "/home/$USER/www/$DOMAIN" ]; then
	mkdir /home/$USER/www/$DOMAIN
fi

if [ ! -d "/home/$USER/www/$DOMAIN/htdocs" ]; then
	mkdir /home/$USER/www/$DOMAIN/htdocs
fi

if [ ! -d "/home/$USER/www/$DOMAIN/html" ]; then
	ln -s /home/$USER/www/$DOMAIN/htdocs /home/$USER/www/$DOMAIN/html
fi

if [ ! -d "/home/$USER/www/$DOMAIN/logs" ]; then
	mkdir /home/$USER/www/$DOMAIN/logs
fi



#set permissions and ownership
chown -R $USER /home/$USER
chmod -R 755 /home/$USER/www
chown -R $USER:www-data /home/$USER/www
chmod 711 /home/$USER

#add the vhosts creation + symlinking and apache cycle
echo "#
#   $DOMAIN ($HTTPD_HOSTS_AVAIL$DOMAIN.conf)
#
<VirtualHost *:80>
        ServerAdmin admin@$DOMAIN
        ServerName $DOMAIN
        ServerAlias www.$DOMAIN *.$DOMAIN

        #Indexes + Directory Root
        DocumentRoot /home/$USER/www/$DOMAIN/htdocs/

        <Directory \"/home/$USER/www/$DOMAIN/html\">
                Options Indexes FollowSymLinks MultiViews
                AllowOverride All
                Order allow,deny
                Allow from all
        </Directory>

        #LOG FILES
        ErrorLog  /home/$USER/www/$DOMAIN/logs/error.log
        CustomLog /home/$USER/www/$DOMAIN/logs/access.log combined
</VirtualHost>" > "$HTTPD_HOSTS_AVAIL$DOMAIN.conf"

ln -s "$HTTPD_HOSTS_AVAIL$DOMAIN.conf" "$HTTPD_HOSTS_EN$DOMAIN.conf"
"$HTTPD_PATH" reload

