#!/bin/bash

if [ -n "$1" ]; then
	echo usage: $0 
	exit
fi

#read some configuration files
source hosting.conf

SPACER="#-----------------------------------------#"

#ln -s "$HTTPD_HOSTS_AVAIL$DOMAIN.conf" "HTTPD_HOSTS_EN$DOMAIN.conf"
#ln -s "$NAMED_HOSTS$DOMAIN" "$NAMED_HOSTS$DOMAIN.hosts"

#get an apache enabled list and output that
APACHE_ENABLED=`ls -1 "$HTTPD_HOSTS_EN" | grep ".conf" | sed s/.conf//`
APACHE_COUNT=`echo -e "$APACHE_ENABLED" | wc -l`
if [ -n "$APACHE_ENABLED" ]; then
 echo $SPACER
 echo "Apache Enabled Sites: $APACHE_COUNT"
 echo "$APACHE_ENABLED" 
else
 echo $SPACER
 echo "There are no detected Apache Enabled Sites"
fi

#get some DNS information
DNS_ZONES=`cat "$NAMED_CONF" | grep -w "zone" | sed 's/.*"\([^"]*\)".*/\1/'`
DNS_COUNT=`echo -e "$DNS_ZONES" | wc -l`
if [ -n "$DNS_ZONES" ]; then
 echo $SPACER
 echo "DNS Hosted Sites: $DNS_COUNT"
 echo "$DNS_ZONES"
else
 echo $SPACER
 echo "There are no detected DNS Hosted Sites"
fi


echo $SPACER
